// Package docs is generated by swag.
//
// In some environments the generated swagger docs are not present.
// This minimal stub keeps the backend buildable; when you generate docs
// (e.g. `swag init`), the real package will replace/extend this.
package docs
